### ISSUE TITLE
Code does not compile

### ISSUE THREAD

**Issue by EricJMarti** [hallamlab/FragGeneScanPlus#1]
I downloaded the source code and tried to compile it. GCC seems to find some type mismatches that prevent the code from compiling. Here is the output: 

[user@hostname FragGeneScanPlus]$ make clean
rm -rf util_lib.o hmm_lib.o run_hmm.o  fasta.o FGS+  
[user@hostname FragGeneScanPlus]$ make
gcc  -O3 -m64 -w -c util_lib.c 
gcc  -O3 -m64 -w -c hmm_lib.c 
gcc  -O3 -m64 -w -c run_hmm.c 
run_hmm.c: In function ‘main’:
run_hmm.c:290:17: error: incompatible type for argument 1 of ‘sem_post’
                 sem_post(thread_datas[j].sema_r);  
                 ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t _’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:302:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(sema_r);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:304:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(sema_Q);  
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:307:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(sema_Q);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:310:13: error: incompatible type for argument 1 of ‘sem_wait’
             sem_wait(sema_R);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:315:13: error: incompatible type for argument 1 of ‘sem_post’
             sem_post(sema_R);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:317:13: error: incompatible type for argument 1 of ‘sem_post’
             sem_post(temp->td->sema_r);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:331:5: error: incompatible type for argument 1 of ‘sem_wait’
     sem_wait(stop_sema);
     ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c: In function ‘writer_func’:
run_hmm.c:550:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(sema_w);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:554:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(sema_Q);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:556:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(sema_Q);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:560:13: error: incompatible type for argument 1 of ‘sem_wait’
             sem_wait(sema_R);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:620:13: error: incompatible type for argument 1 of ‘sem_post’
             sem_post(sema_R);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:621:13: error: incompatible type for argument 1 of ‘sem_post’
             sem_post(td->sema_w);
             ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:635:11: error: incompatible type for argument 1 of ‘sem_post’
           sem_post(stop_sema);
           ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c: In function ‘thread_func’:
run_hmm.c:649:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(td->sema_r);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:650:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(td->sema_w);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:653:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(counter_sema);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:655:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(counter_sema);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:682:17: error: incompatible type for argument 1 of ‘sem_wait’
                 sem_wait(work_sema);
                 ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:684:17: error: incompatible type for argument 1 of ‘sem_post’
                 sem_post(work_sema);
                 ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:691:9: error: incompatible type for argument 1 of ‘sem_wait’
         sem_wait(sema_Q);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:55:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_wait (sem_t *__sem);
            ^
run_hmm.c:695:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(sema_Q);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:696:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(sema_r);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
run_hmm.c:697:9: error: incompatible type for argument 1 of ‘sem_post’
         sem_post(sema_w);
         ^
In file included from hmm.h:13:0,
                 from run_hmm.c:1:
/usr/include/semaphore.h:70:12: note: expected ‘union sem_t *’ but argument is of type ‘SEM_T’
 extern int sem_post (sem_t *__sem) __THROW;
            ^
make: *_\* [run_hmm.o] Error 1

**Comment by dongjaek** [comment]
Hi Eric,

the problem should be fixed, it was from when I was refactoring something out of the Makefile to remove flag dependency. It should compile on Linux and Mac with no problems now. If there still is something wrong with the compilation and running please let us know!

**Comment by EricJMarti** [comment]
The program compiled and I was able to use it. Thanks!
