### ISSUE TITLE
Bug when command line arguments are provided in a particular order

### ISSUE THREAD

**Issue by stelllaras** [hallamlab/FragGeneScanPlus#2]
When providing -r (train dir) after -t (train file name), FGS+ will check the existence of the train file prior to adjusting the train dir, wrongly resulting in an error.

Lines 134-140 in run_hmm.c should be placed after the while() loop.

**Comment by dongjaek** [comment]
Thank you I will push a fix soon.

**Comment by dongjaek** [comment]
fixed
