### ISSUE TITLE
standard input/output support

### ISSUE THREAD

**Issue by bmesuere** [hallamlab/FragGeneScanPlus#3]
Are there any plans to also support standard input and output instead of only files? This way, FGS+ could be used in an actual unix pipeline and run in parallel with other post- and preprocessing steps.

ps. There are a few layout/markdown issues with the wiki page. Adding a few backticks/code blocks here and there would clean it up.

**Comment by dongjaek** [comment]
I will look into supporting stdin/stdout as well as fixing the github wiki problems in the near future.

**Comment by dongjaek** [comment]
I have added support for stdin and stdout. The help and the wiki have been updated accordingly to reflect how to use these new features.
