### ISSUE TITLE
Also search for training sets relative to the FGS+ directory

### ISSUE THREAD

**Issue by Procrat** [hallamlab/FragGeneScanPlus#4]
First of all, thank you for maintaining FGS+!

Right now, the `-t` option searches for training sets in the `train` subdirectory of the current working directory. Wouldn't it be useful to let this default to the directory of FGS+? I presume that most users would like to use the provided training sets. In that case, this would be the desired behavior when executing FGS+ from another directory.

I can make a pull request with these changes if you want.

**Comment by dongjaek** [comment]
Hi Procat,

thank you for the suggestion, it is indeed sensible, however I think it would be best to leave it as it is for backwards compatibility issues as users would expect the parameter usage to remain with what they are used to. The wiki and the documentation should be enough to prepare the user on how to use FGS+.
