### ISSUE TITLE
Running outside the folder adding the extra /train

### ISSUE THREAD

**Issue by raw937** [hallamlab/FragGeneScanPlus#9]
FGS+ -s ~/test/Test_contigs.fna -o ~test/Test_contigs_Illumina_10 -w 0 -t ~/FragGeneScanPlus/train/illumina_10 -p 24 -m 30000
ERROR: The file for model parameters [train//people/whit040/ATLAS_pipeline/FragGeneScanPlus/train/illumina_10] does not exist

How can I fix this?

**Comment by dongjaek** [comment]
Not intending to change in order to keep compatibility with FragGeneScan which decided to make the user run from the FragGeneScan directory. 

Updated the help statement produced by the tool and wiki documentation.
